language: crystal
script:
- crystal spec
- crystal docs
services:
- postgresql
before_script:
- psql -V
addons:
  postgresql: '9.6'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  project_name: anykeyh/clear
  on:
    branch: master
  local_dir: docs
env:
  global:
    secure: FuELrhXQOsmvL1EDSA1z14vBg25MAhIVR/sPv9Zhd1R3wyMku6oG2DZ8/0tk1B818rH52Z54/vDV54hB1TBKfOYHSTu1Yq4Bp9HQIzXuLSKp0RquT9feNoNXBXtSI73kR7Ic4JOV3+lPj2wGpqp0rmvFR+gIo4A0yJuViWPQcsok7SDJULfsqdHGV9ffglm40bja6H9qJvlGuXZiSEpJdrjBpWprN3f6vtWaG/38FjgH8F1Pot5jCfLBuIOQuB59qxdBhgr6KYdrNLZGVXFhsBuUUvvBIliBGn0SKYeAwj1y0LudxqOXNXgNOJhNv7b2/ZdIpVpabMs3Yntn8JHuub1Uo6KdzTmpvUeJuIjrmXReXxo4/vkHYjs4gYUDUQ95p89wWP96M0TBincrSiPXiqiPC4I82EoyE3CRQ92Nh+udywuYRBWZ2+WIsT5RNPmW1WwhFdhqiOlYn2Sk8AwI95JcMQ5UsiXp6U2YL53ytgnmMCToYHbS+4Qkwu32iaix2MVd5/ufVmwCxT1QDdFsX8SmUpCOritjPhYI11qGeSlNynNR69nrLHCbbpLdHwrWWxu3yNOi2Gh6Khps2HOuVtw+H2RTwLi2Mi3BBEiw0Rc+hMtN1e4kE0e1ytMRo7u+6AUKWkZZAjXlo9bXE9A/DGJw9lYYIyLykiWxilFMbQ0=
